_wandb:
    value:
        cli_version: 0.23.1
        e:
            hsx0piu6yy4ydewrfoahl28070jjftss:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "244939624448"
                        used: "13074718720"
                email: syal.6cyu@gmail.com
                executable: /home/wundari/VLM/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-6546df29-c39a-260b-736a-1a5061c45feb
                host: wundari
                memory:
                    total: "49730060288"
                os: Linux-6.17.0-35-generic-x86_64-with-glibc2.39
                program: /home/wundari/nanoVLM_HF_v2/train.py
                python: CPython 3.14.1
                root: /home/wundari/nanoVLM_HF_v2
                startedAt: "2026-06-04T13:23:26.376642Z"
                writerId: hsx0piu6yy4ydewrfoahl28070jjftss
        m:
            - "2": lmms_eval/*
              "5": 2
              "6":
                - 1
              "7": []
            - "1": <lmms-eval-step>
              "6": []
              "7": []
        python_version: 3.14.1
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "3":
                - 7
                - 13
                - 16
                - 61
            "4": 3.14.1
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
TrainConfig:
    value:
        batch_size: 1
        compile: false
        eval_in_epochs: true
        eval_interval: 5000
        formatting_min_rating: 1
        gradient_accumulation_steps: 8
        image_correspondence_min_rating: 1
        lmms_eval_batch_size: 64
        lmms_eval_limit: null
        lmms_eval_tasks: mmstar,mmmu_val,ocrbench,textvqa_val,docvqa_val,scienceqa,mme,infovqa_val,chartqa
        log_wandb: true
        lr_language_backbone: 5e-05
        lr_mp: 0.00512
        lr_vision_backbone: 5e-05
        max_grad_norm: 1
        max_images_per_example: 4
        max_images_per_knapsack: 18
        max_sample_length: 4096
        max_training_steps: 40000
        relevance_min_rating: 1
        resume_from_vlm_checkpoint: false
        stats_log_interval: 100
        stream_dataset: true
        train_dataset_name:
            - all
        train_dataset_path: HuggingFaceM4/FineVision
        use_lmms_eval: true
        val_size: 50000
        visual_dependency_min_rating: 1
        wandb_entity: 6cyu
VLMConfig:
    value:
        extra_token_amount: 66
        hf_repo_name: nanoVLM
        lm_attn_scaling: 1
        lm_base_vocab_size: 49152
        lm_chat_template: |-
            {% for message in messages %}{{'<|im_start|>' + message['role'] + '
            ' + message['content'] + '<|im_end|>' + '
            '}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
            ' }}{% endif %}
        lm_dropout: 0
        lm_hidden_dim: 960
        lm_inter_dim: 2560
        lm_max_length: 4096
        lm_max_position_embeddings: 8192
        lm_model_type: HuggingFaceTB/SmolLM2-360M-Instruct
        lm_n_blocks: 32
        lm_n_heads: 15
        lm_n_kv_heads: 5
        lm_re_base: 100000
        lm_rms_eps: 1e-05
        lm_tie_weights: true
        lm_tokenizer: HuggingFaceTB/SmolLM2-360M-Instruct
        lm_use_tokens: false
        lm_vocab_size: 49218
        max_img_size: 2048
        mp_image_token_length: 64
        mp_pixel_shuffle_factor: 4
        resize_to_max_side_len: true
        vit_cls_flag: false
        vit_dropout: 0
        vit_hidden_dim: 768
        vit_img_size: 512
        vit_inter_dim: 3072
        vit_ln_eps: 1e-06
        vit_model_type: google/siglip2-base-patch16-512
        vit_n_blocks: 12
        vit_n_heads: 12
        vit_patch_size: 16
        vlm_checkpoint_path: checkpoints
        vlm_extra_tokens:
            global_image_token: <|global_image|>
            image_token: <|image|>
            r1c1: <row_1_col_1>
            r1c2: <row_1_col_2>
            r1c3: <row_1_col_3>
            r1c4: <row_1_col_4>
            r1c5: <row_1_col_5>
            r1c6: <row_1_col_6>
            r1c7: <row_1_col_7>
            r1c8: <row_1_col_8>
            r2c1: <row_2_col_1>
            r2c2: <row_2_col_2>
            r2c3: <row_2_col_3>
            r2c4: <row_2_col_4>
            r2c5: <row_2_col_5>
            r2c6: <row_2_col_6>
            r2c7: <row_2_col_7>
            r2c8: <row_2_col_8>
            r3c1: <row_3_col_1>
            r3c2: <row_3_col_2>
            r3c3: <row_3_col_3>
            r3c4: <row_3_col_4>
            r3c5: <row_3_col_5>
            r3c6: <row_3_col_6>
            r3c7: <row_3_col_7>
            r3c8: <row_3_col_8>
            r4c1: <row_4_col_1>
            r4c2: <row_4_col_2>
            r4c3: <row_4_col_3>
            r4c4: <row_4_col_4>
            r4c5: <row_4_col_5>
            r4c6: <row_4_col_6>
            r4c7: <row_4_col_7>
            r4c8: <row_4_col_8>
            r5c1: <row_5_col_1>
            r5c2: <row_5_col_2>
            r5c3: <row_5_col_3>
            r5c4: <row_5_col_4>
            r5c5: <row_5_col_5>
            r5c6: <row_5_col_6>
            r5c7: <row_5_col_7>
            r5c8: <row_5_col_8>
            r6c1: <row_6_col_1>
            r6c2: <row_6_col_2>
            r6c3: <row_6_col_3>
            r6c4: <row_6_col_4>
            r6c5: <row_6_col_5>
            r6c6: <row_6_col_6>
            r6c7: <row_6_col_7>
            r6c8: <row_6_col_8>
            r7c1: <row_7_col_1>
            r7c2: <row_7_col_2>
            r7c3: <row_7_col_3>
            r7c4: <row_7_col_4>
            r7c5: <row_7_col_5>
            r7c6: <row_7_col_6>
            r7c7: <row_7_col_7>
            r7c8: <row_7_col_8>
            r8c1: <row_8_col_1>
            r8c2: <row_8_col_2>
            r8c3: <row_8_col_3>
            r8c4: <row_8_col_4>
            r8c5: <row_8_col_5>
            r8c6: <row_8_col_6>
            r8c7: <row_8_col_7>
            r8c8: <row_8_col_8>
        vlm_load_backbone_weights: true
